import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `
(() => {
  if (window.__omingloEscapeShortcut) return;
  window.__omingloEscapeShortcut = true;

  document.addEventListener("keydown", (event) => {
    if (event.key !== "Escape" || event.repeat || event.defaultPrevented) return;
    if (event.altKey || event.ctrlKey || event.metaKey) return;
    if (!document.querySelector(".um-video-page")) return;
    if (event.target instanceof HTMLSelectElement) return;

    const control = document.querySelector(".um-video-page .um-start-button");
    if (!(control instanceof HTMLButtonElement) || control.disabled) return;

    event.preventDefault();
    control.click();
  }, true);
})();
            `.trim(),
          }}
        />
      </body>
    </html>
  );
}
